name: Publish NuGet Packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-core:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore KarizmaCore dependencies
        run: dotnet restore KarizmaCore/KarizmaCore.csproj

      - name: Build KarizmaCore project
        run: dotnet build KarizmaCore/KarizmaCore.csproj --configuration Release --no-restore

      - name: Pack KarizmaCore project
        run: dotnet pack KarizmaCore/KarizmaCore.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish KarizmaCore package to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.KARIZMACORE_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.KARIZMACORE_API_KEY }}
